// Generates src/styles/tokens.css from tokens/figma-variables.json.
// The JSON is a read-only export of the Figma file's local variables and styles.
// Never edit tokens.css by hand: re-export from Figma and run `npm run tokens`.
//
// Naming follows design.md §2.2:
//   color/slate/500      -> --color-slate-500        (base, NOT exposed as utilities)
//   text/primary         -> --color-text-primary     -> utility .text-primary
//   background/surface   -> --color-background-surface -> utility .bg-surface
//   border/default       -> --color-border-default   -> utility .border-default
//   spacing/4            -> Tailwind spacing scale (4px step)  -> p-4, gap-4
//   radius/2xl           -> --radius-2xl             -> rounded-2xl
// Base colours stay out of Tailwind's theme on purpose (design.md §2.4: UI must not
// bind base colours). Only semantic roles become classes.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(join(root, 'tokens/figma-variables.json'), 'utf8'));
// Code-first tokens waiting to be created in Figma (see the file's _note). Kept separate so the export stays a pure Figma copy.
const pending = JSON.parse(readFileSync(join(root, 'tokens/pending-figma.json'), 'utf8'));
const out = join(root, 'src/styles/tokens.css');

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const cssVar = (name) => '--' + name.replace(/\//g, '-').replace(/_/g, '-');
const semVar = (name) => '--color-' + name.replace(/\//g, '-');
const px = (n) => (n === 0 ? '0' : `${n}px`);

const col = (n) => src.collections.find((c) => c.name === n).vars;
const base = col('Base / Color');
const semantic = col('Semantic / Color');
const radius = col('Base / Radius');
const spacing = col('Base / Spacing');
const shape = col('Semantic / Shape');
const sizes = col('Semantic / Size');
const spacingPx = new Map(spacing.map(([n, v]) => [n, v]));

const value = (v) => (typeof v === 'string' && v.startsWith('@') ? `var(${cssVar(v.slice(1))})` : v);

const lines = [];
lines.push('/* GENERATED by scripts/build-tokens.mjs from tokens/figma-variables.json. Do not edit. */');
lines.push(`/* ${src._source} */`, '');

// 1. Base colours: plain custom properties, no utilities.
lines.push(':root {');
for (const [n, v] of base) lines.push(`  ${cssVar(n)}: ${v};`);
lines.push('');
// 2. Semantic colours alias base colours.
for (const [n, v] of semantic) lines.push(`  ${semVar(n)}: ${value(v)};`);
lines.push('}', '');

// 3. Tailwind theme: wipe the default palette so only semantic utilities exist.
lines.push('@theme {');
lines.push('  --color-*: initial;');
lines.push('  --color-transparent: transparent;');
lines.push('  --color-current: currentColor;');
lines.push('  --spacing: 4px;');
for (const [n, v] of radius) {
  const key = n.split('/')[1];
  if (key === 'none') continue;
  lines.push(`  --radius-${key}: ${key === 'full' ? 'calc(infinity * 1px)' : px(v)};`);
}
// Role radii alias the base scale (Figma `Semantic / Shape`): rounded-control, rounded-container…
for (const [n, v] of shape) lines.push(`  --radius-${n.split('/')[1]}: var(--radius-${v.slice(1).split('/')[1]});`);
// Font roles come from the text styles, not from code: headers -> heading, body -> body, any Mono family -> mono.
const famOf = (re) => src.textStyles.find(([n, f]) => re.test(n) && !/Mono/.test(f))?.[1];
const fonts = { heading: famOf(/Header/), body: famOf(/Body/), mono: src.textStyles.find(([, f]) => /Mono/.test(f))?.[1] };
const fontVar = (name, family) => (/Mono/.test(family) ? 'var(--font-mono)' : /Header/.test(name) ? 'var(--font-heading)' : 'var(--font-body)');
lines.push(`  --font-heading: '${fonts.heading}', ui-sans-serif, system-ui, sans-serif;`);
lines.push(`  --font-body: '${fonts.body}', ui-sans-serif, system-ui, sans-serif;`);
if (fonts.mono) lines.push(`  --font-mono: '${fonts.mono}', ui-monospace, monospace;`);
lines.push("  --font-sans: var(--font-body);");
const shadow = (layers) =>
  layers
    .map(([t, c, x, y, b, s]) => `${t === 'inner' ? 'inset ' : ''}${px(x)} ${px(y)} ${px(b)} ${px(s)} ${c}`)
    .join(', ');
for (const [n, layers] of src.effectStyles) {
  // Focus State: CSS paints the first shadow on top, so the white gap (smaller spread)
  // goes first and the blue ring second. Figma stores the layers in the opposite order.
  if (n === 'Focus State') lines.push(`  --shadow-focus: ${shadow([...layers].sort((a, b) => a[5] - b[5]))};`);
  // `Box Shadow/shadow` (no size) becomes shadow-base so the class name is explicit.
  else lines.push(`  --${n.split('/')[1].replace(/^shadow$/, 'shadow-base')}: ${shadow(layers)};`);
}
lines.push('}', '');

// 4. Semantic colour utilities, one family per Figma group (design.md §2.2).
const fam = {
  text: ['text', 'color'],
  background: ['bg', 'background-color'],
  border: ['border', 'border-color'],
  // icon/* sets `color`: icons draw with currentColor, so the class goes on the icon or its wrapper.
  icon: ['icon', 'color'],
};
for (const [n] of semantic) {
  const [group, role] = n.split('/');
  const [prefix, prop] = fam[group];
  lines.push(`@utility ${prefix}-${role} { ${prop}: var(${semVar(n)}); }`);
}
// Text tokens may be used on strokes and fills (design.md §2.3): icon helpers.
for (const [n] of semantic.filter(([n]) => n.startsWith('text/'))) {
  const role = n.split('/')[1];
  lines.push(`@utility stroke-${role} { stroke: var(${semVar(n)}); }`);
  lines.push(`@utility fill-${role} { fill: var(${semVar(n)}); }`);
}
// Role sizes (Figma `Semantic / Size`, aliases of the spacing scale): h-control-lg, min-h-target-min…
lines.push(':root {');
for (const [n, v] of sizes) lines.push(`  --${n.replace('/', '-')}: ${px(spacingPx.get(v.slice(1)))}; /* ${v.slice(1)} */`);
lines.push('}');
for (const [n] of sizes) {
  const k = n.split('/')[1];
  if (k.startsWith('iso-')) continue; // lattice cell sizes are read as CSS variables by IsoGrid, not used as box sizes
  lines.push(`@utility h-${k} { height: var(--size-${k}); }`);
  lines.push(`@utility min-h-${k} { min-height: var(--size-${k}); }`);
  lines.push(`@utility size-${k} { width: var(--size-${k}); height: var(--size-${k}); }`);
}
// Content widths (pending in Figma): max-w-content-narrow, max-w-content-default.
if (pending.sizes.length) {
  lines.push('/* Pending in Figma: tokens/pending-figma.json */', ':root {');
  for (const [n, v, use] of pending.sizes) lines.push(`  --${n.replace('/', '-')}: ${px(v)}; /* ${use} */`);
  lines.push('}');
  for (const [n] of pending.sizes) {
    const k = n.split('/')[1];
    lines.push(`@utility max-w-${k} { max-width: var(--size-${k}); }`);
  }
  console.warn(`⚠ ${pending.sizes.length} token(s) exist only in code (tokens/pending-figma.json): ${pending.sizes.map(([n]) => n).join(', ')}`);
}
lines.push('');

// 5. Text styles -> one utility each, named after the Figma path.
for (const [name, family, weight, size, lh, ls, textCase] of src.textStyles) {
  const decl = [
    `font-family: ${fontVar(name, family)}`,
    `font-weight: ${weight}`,
    `font-size: ${px(size)}`,
    `line-height: ${lh == null ? 'normal' : px(lh)}`,
    `letter-spacing: ${ls ? ls / 100 + 'em' : '0'}`,
    ...(textCase === 'UPPER' ? ['text-transform: uppercase'] : textCase === 'LOWER' ? ['text-transform: lowercase'] : []),
  ].join('; ');
  lines.push(`@utility type-${slug(name)} { ${decl}; }`);
}

// Spacing check: every Figma spacing step must equal step × 4px (Tailwind scale).
const off = spacing.filter(([n, v]) => {
  const step = n.split('/')[1];
  if (step === 'px') return v !== 1;
  return Number(step.replace('_', '.')) * 4 !== v;
});
if (off.length) {
  console.error('Spacing tokens off the 4px scale:', off);
  process.exit(1);
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join('\n') + '\n');
console.log(`tokens.css: ${base.length} base colours, ${semantic.length} semantic, ${shape.length} role radii, ${sizes.length} role sizes, ${radius.length} radii, ${spacing.length} spacing steps (checked), ${src.textStyles.length} text styles, ${src.effectStyles.length} effects`);
